### ISSUE TITLE
Apps table issues

### ISSUE THREAD

**Issue by vboiteau** [gti525/h17-analytique-publicite#15]
- name row not set event if in POST payload;
- PUT and DELETE aren't working like others table (tags, campains)

**Comment by max611** [comment]
Fixed ici: https://github.com/gti525/h17-analytique-publicite/commit/b0d935d5326d978c527611adffa6c58eb9d22d6e

Est ce que tu peux tester pour être sur? :P

**Comment by vboiteau** [comment]
All good
