### ISSUE TITLE
Ajout de l'url pour associer manuellement un tag

### ISSUE THREAD

**Issue by julienlemonde** [gti525/h17-analytique-publicite#22]
Je mets Vincent aussi au pour faire la modifs frontend

**Comment by max611** [comment]
Done du coté backend, faudrait faire un petit formulaire

Ex avec curl: `curl -H "Content-Type: application/json" -X POST -d '{"url": "http://localhost:3001/events/1/teams", "tag": "geek", "app_id":1}' http://localhost:3000/urls`

**Comment by vboiteau** [comment]
C'est pas exactement le concept des campagnes.
