### ISSUE TITLE
Comptabiliser le nombre de vues et cliques pour chaque pub

### ISSUE THREAD

**Issue by julienlemonde** [gti525/h17-analytique-publicite#23]

**Comment by julienlemonde** [comment]
Raph pour les pubs non ciblés
François pour les pubs ciblés.

En fait les deux sont relativement semblable dans le backend mais doit avoir des données indépendantes.

**Comment by francoisgelinas1** [comment]
Reste plus qu'à comptabiliser le nombre de view pour les campagnes

**Comment by max611** [comment]
Done, avec Vincent on va toujours passer le `campaign_id` donc on va pouvoir comptabiliser facilement
