### ISSUE TITLE
Téléverser pub (Image et url) pour être utiliser par le site

### ISSUE THREAD

**Issue by julienlemonde** [gti525/h17-analytique-publicite#24]
Vincent pour le frontend
Max et Julien pour le backend, il faut créer une table pour

**Comment by vboiteau** [comment]
url de l'image et du contenu sur le quelle elle redirige. Je peux ajouter le upload des images si vous me dites l'url pour push j'ai fait ca pour ma job 4-5 fois 1 histoire de 30min en frontend

**Comment by vboiteau** [comment]
Done, up and working.
