### ISSUE TITLE
Déterminer le montant des dividendes

### ISSUE THREAD

**Issue by julienlemonde** [gti525/h17-analytique-publicite#26]
Doit être fait à la fin quand on a toutes les données recueillis
Calcule: 
pub de la campagne vu = 0,14$/visite
Publicité cliquée non ciblée: 0,05$/clique
Publicité cliquée ciblé: 0,10$/clique

Le tous afficher pour la campagne en cours

**Comment by max611** [comment]
Fait et disponible dans `/apps/id` dans la section `ads_money `

**Comment by max611** [comment]
Fait ici: https://github.com/gti525/h17-analytique-publicite/commit/b0d935d5326d978c527611adffa6c58eb9d22d6e
