### ISSUE TITLE
PUT /infos/:info_item_id

### ISSUE THREAD

**Issue by vboiteau** [gti525/h17-analytique-publicite#31]

**Comment by RaphIng** [comment]
Update de l'objet infos quand tu nous passe le info_item_id ?

**Comment by vboiteau** [comment]
Donc, au début on envoyait le POST au close de la page. Mais ce que je savais pas c’est que c’est que l’event de unload de la page se fou complétement des requête async, donc la page closais avant de recevoir confirme du serveur. Donc si on restait sur la page no prob, mais maintenant que j’ai enlever l’alert pour le debug ça write jamais en DB vu que c’est une action async.
Donc, ma solution est d’envoyer les datas à toutes les 2 secondes.

[12:53]  
donc je veux pas envahir la db avec des lignes de infos, ca prend donc un put.

**Comment by RaphIng** [comment]
Good, je comprend.
C'est a tester donc fait
