### ISSUE TITLE
Ajouter total des redevances pour les campagnes et les apps

### ISSUE THREAD

**Issue by vboiteau** [gti525/h17-analytique-publicite#38]
Pour finaliser l'ajout des données dynamiques dans le frontend, il faudrait ajouter un total des redevances lors d'une requêtes GET sur chacune des collections.
GET /campaigns
GET /apps

**Comment by max611** [comment]
Fix here: https://github.com/gti525/h17-analytique-publicite/commit/eda92b715f8a57671b41e9694e1251ed0e81a7a5
