### ISSUE TITLE
[GET] return an ads

### ISSUE THREAD

**Issue by max611** [gti525/h17-analytique-publicite#4]
Return an ad when a user connect to the website

**Comment by RaphIng** [comment]
1 - User visit register website
2 - Client side js ask for ads for this user
if(know user)
2.1 return custom ad
else
2.2 return ad 

that right ?

**Comment by max611** [comment]
done here: https://github.com/gti525/h17-analytique-publicite/blob/master/app/controllers/ads_controller.rb#L11
